import '@/styles/styles.scss';
import StoreProvider from '@/app/StoreProvider';
import ThemeProvider from '../components/themeProvider/ThemeProvider';
import ThemeToggle from '@/components/themeProvider/ThemeToggle';
import AuthProvider from '@/components/context/AuthProvider';
import { Toaster } from '@/components/ui/sonner';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <StoreProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <ThemeToggle />
            <AuthProvider>
              <>{children}</>
            </AuthProvider>
          </ThemeProvider>
        </StoreProvider>
        <Toaster />
      </body>
    </html>
  );
}
