import '@/styles/styles.scss';
import Provider from '@/services/redux/Provider';
import ThemeProvider from '../components/themeProvider/ThemeProvider';
import ThemeToggle from '@/components/themeProvider/ThemeToggle';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <ThemeToggle />
            <>{children}</>
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  );
}
